name: weather_app
description: "A new Flutter project."
 
publish_to: 'none' 

 
version: 1.0.0+1

environment:
  sdk: ^3.5.3
 
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  
 
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.10+1
  animated_text_kit: ^4.2.2
  dio: ^5.7.0
  retry: ^3.1.2
  get: ^4.6.6
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

 
flutter: 
  uses-material-design: true
  assets:
    - assets/background/
    - assets/icons/
  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
